apiVersion: v1
kind: Service
metadata:
  name: {{ include "sluice.name" . }}
  labels:
    {{- include "sluice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sluice.selector" . | nindent 4 }}
  ports:
    - name: control
      port: {{ .Values.service.controlPort }}
      targetPort: control
    {{- range $i, $port := .Values.service.sourcePorts }}
    - name: source-{{ $i }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}