//! `vector.yaml`: the data plane as a Vector configuration, with unit tests.
//!
//! Per source, events flow:
//!
//! ```text
//! input ─┬─▶ archive (full fidelity, before any reduction: safety contract rule 2)
//!        └─▶ sluice_<src> (the proven VRL) ─▶ route ─┬─ forward ───▶ SIEM sink
//!                  │ errors                           └─ summarize ─▶ summary record ─▶ reduce ─▶ sink
//!                  └──────────────────────────────────────────────────▶ SIEM sink (unmodified)
//! ```
//!
//! An event the program fails on is forwarded unmodified (`reroute_dropped`), and so is any event
//! the route does not match: the data plane fails open for forwarding.
//!
//! The generated unit tests replay sample events through `sluice_<src>` and assert the outcome
//! the `vrl` crate computed for the proof. `vector test` then shows that the Vector binary does
//! exactly what was proven.

use std::collections::BTreeSet;

use serde_json::{Map, Value, json};
use sluice_core::event::Event;
use sluice_core::guard::Route;
use sluice_core::ids::{SourceId, TemplateId};
use sluice_core::reduce::{Outcome, Reducer};
use sluice_core::source::Source;

use crate::error::VectorError;
use crate::program::{FORWARD, Plan, ROUTE_METADATA, SUMMARIZE, TEMPLATE_METADATA};
use crate::runtime::VrlReducer;
use crate::syntax;

/// Where the demo configuration reads and writes files.
#[derive(Debug, Clone)]
pub struct Paths {
    /// Directory holding one `<source>.ndjson` input file per source.
    pub input_dir: String,
    /// Directory receiving the archive, forwarded events and summaries.
    pub output_dir: String,
}

/// How long a summary window stays open, in milliseconds.
const SUMMARY_WINDOW_MS: u64 = 60_000;

/// Renders the Vector configuration for `sources`, with unit tests drawn from `events`.
///
/// # Errors
///
/// Returns [`VectorError::Config`] if a sample event cannot be reduced (a Sluice bug).
pub fn vector_config(
    sources: &[Source],
    plans: &[Plan<'_>],
    data_plane: &VrlReducer,
    events: &[Event],
    paths: &Paths,
) -> Result<String, VectorError> {
    let mut pipeline = Pipeline::default();
    for source in sources {
        if let Some(program) = data_plane.program(&source.id) {
            pipeline.add_source(source, program.source(), plans, paths);
        }
    }
    let config = json!({
        "data_dir": format!("{}/vector-data", paths.output_dir),
        "sources": pipeline.sources,
        "transforms": pipeline.transforms,
        "sinks": pipeline.sinks,
        "tests": unit_tests(data_plane, plans, events)?,
    });
    let yaml = serde_yaml_ng::to_string(&config).map_err(|e| VectorError::Config(e.to_string()))?;
    Ok(format!(
        "# Generated by Sluice. Do not edit: regenerate with `sluice analyze`.\n\
         # Check with: vector validate --no-environment vector.yaml && vector test vector.yaml\n{yaml}"
    ))
}

/// The three component sections of a Vector configuration.
#[derive(Default)]
pub(crate) struct Pipeline {
    pub(crate) sources: Map<String, Value>,
    pub(crate) transforms: Map<String, Value>,
    pub(crate) sinks: Map<String, Value>,
}

impl Pipeline {
    fn add_source(&mut self, source: &Source, program: &str, plans: &[Plan<'_>], paths: &Paths) {
        let c = Components::for_source(&source.id);
        self.sources.insert(
            c.input.clone(),
            json!({
                "type": "file",
                "include": [format!("{}/{}.ndjson", paths.input_dir, source.id)],
                "read_from": "beginning",
            }),
        );
        self.transforms.insert(
            c.parse.clone(),
            json!({
                "type": "remap",
                "inputs": [c.input],
                "source": ". = parse_json!(string!(.message))",
            }),
        );
        self.add_transforms(&c, &c.parse, &source.id, program, plans);
        let out = |kind: &str| format!("{}/{kind}/{}.ndjson", paths.output_dir, source.id);
        let archive = format!(
            "{}/archive/{}/%Y-%m-%d-%H.ndjson",
            paths.output_dir, source.id
        );
        self.sinks.insert(
            c.archive_sink(),
            file_sink(std::slice::from_ref(&c.parse), &archive),
        );
        let forwarded = [
            format!("{}.{FORWARD}", c.split),
            format!("{}._unmatched", c.split),
            format!("{}.dropped", c.program),
        ];
        self.sinks
            .insert(c.forward_sink(), file_sink(&forwarded, &out("forward")));
        self.sinks.insert(
            c.summary_sink(),
            file_sink(std::slice::from_ref(&c.summaries), &out("summaries")),
        );
    }

    /// The reduction transforms of one source, fed by the component `entry`.
    pub(crate) fn add_transforms(
        &mut self,
        c: &Components,
        entry: &str,
        source: &SourceId,
        program: &str,
        plans: &[Plan<'_>],
    ) {
        let route_on =
            |route: &str| format!("%sluice.{ROUTE_METADATA} == {}", syntax::string(route));
        let transforms = [
            (
                &c.program,
                json!({
                    "type": "remap",
                    "inputs": [entry],
                    "source": program,
                    "drop_on_error": true,
                    "reroute_dropped": true,
                }),
            ),
            (
                &c.split,
                json!({
                    "type": "route",
                    "inputs": [c.program],
                    "route": { FORWARD: route_on(FORWARD), SUMMARIZE: route_on(SUMMARIZE) },
                }),
            ),
            (
                &c.summarize,
                json!({
                    "type": "remap",
                    "inputs": [format!("{}.{SUMMARIZE}", c.split)],
                    "source": summary_program(source, plans),
                }),
            ),
            (
                &c.summaries,
                json!({
                    "type": "reduce",
                    "inputs": [c.summarize],
                    "group_by": ["sluice_group"],
                    "merge_strategies": { "sluice_count": "sum" },
                    // A steady stream never goes idle, so close every group each window too.
                    "expire_after_ms": SUMMARY_WINDOW_MS,
                    "end_every_period_ms": SUMMARY_WINDOW_MS,
                }),
            ),
        ];
        for (id, transform) in transforms {
            self.transforms.insert(id.clone(), transform);
        }
    }
}

/// Component ids of one source's pipeline.
pub(crate) struct Components {
    pub(crate) stem: String,
    pub(crate) input: String,
    pub(crate) parse: String,
    pub(crate) program: String,
    pub(crate) split: String,
    pub(crate) summarize: String,
    pub(crate) summaries: String,
}

impl Components {
    pub(crate) fn for_source(source: &SourceId) -> Self {
        let stem: String = source
            .as_str()
            .chars()
            .map(|c| {
                if c.is_ascii_alphanumeric() {
                    c.to_ascii_lowercase()
                } else {
                    '_'
                }
            })
            .collect();
        let name = |suffix: &str| format!("sluice_{stem}{suffix}");
        Self {
            input: name("_input"),
            parse: name("_parse"),
            program: name(""),
            split: name("_route"),
            summarize: name("_summarize"),
            summaries: name("_summaries"),
            stem,
        }
    }

    pub(crate) fn archive_sink(&self) -> String {
        format!("sluice_{}_archive", self.stem)
    }

    fn forward_sink(&self) -> String {
        format!("sluice_{}_forward", self.stem)
    }

    fn summary_sink(&self) -> String {
        format!("sluice_{}_summary", self.stem)
    }
}

fn file_sink(inputs: &[String], path: &str) -> Value {
    json!({
        "type": "file",
        "inputs": inputs,
        "path": path,
        "encoding": { "codec": "json" },
    })
}

/// Rewrites a summarized event into a summary record keyed by its template's summary keys.
fn summary_program(source: &SourceId, plans: &[Plan<'_>]) -> String {
    let mut lines = vec!["_sluice_keys = {}".to_owned()];
    for plan in plans.iter().filter(|p| &p.template.source == source) {
        let Route::ForwardMatching { summary_keys, .. } = &plan.recipe.route else {
            continue;
        };
        let keys: Vec<String> = summary_keys
            .iter()
            .map(|k| format!("{}: {}", syntax::string(k.as_str()), syntax::path(k)))
            .collect();
        lines.push(format!(
            "if %sluice.{TEMPLATE_METADATA} == {} {{ _sluice_keys = {{ {} }} }}",
            syntax::string(plan.template.id.as_str()),
            keys.join(", ")
        ));
    }
    lines.push(format!(
        "_sluice_template = string(%sluice.{TEMPLATE_METADATA}) ?? \"\"\n\
         . = {{ \"sluice_summary\": true, \"sluice_source\": {}, \"sluice_template\": _sluice_template, \
         \"sluice_keys\": _sluice_keys, \"sluice_count\": 1 }}\n\
         .sluice_group = _sluice_template + \"|\" + encode_json(_sluice_keys)",
        syntax::string(source.as_str())
    ));
    let mut program = lines.join("\n");
    program.push('\n');
    program
}

/// One test per reducing template and outcome (summarized, forwarded reduced, forwarded whole:
/// both sides of a conditional protection), plus one pass-through test per source, each
/// asserting what the `vrl` crate computed.
fn unit_tests(
    data_plane: &VrlReducer,
    plans: &[Plan<'_>],
    events: &[Event],
) -> Result<Vec<Value>, VectorError> {
    let reducing_templates: BTreeSet<&TemplateId> = plans
        .iter()
        .filter(|p| !p.recipe.is_passthrough())
        .map(|p| &p.template.id)
        .collect();
    let mut seen: BTreeSet<(SourceId, Option<TemplateId>, &str, bool)> = BTreeSet::new();
    let mut tests = Vec::new();
    for event in events {
        if data_plane.program(&event.source).is_none() {
            continue;
        }
        let reduced = data_plane
            .reduce(event)
            .map_err(|e| VectorError::Config(e.to_string()))?;
        let (route, expected) = match &reduced.outcome {
            Outcome::Forwarded(body) => (FORWARD, body),
            Outcome::Summarized => (SUMMARIZE, &event.fields),
        };
        let has_reduction = reduced
            .template
            .as_ref()
            .is_some_and(|t| reducing_templates.contains(t));
        // Pass-through events: one test per source, whatever their template.
        let key_template = if has_reduction {
            reduced.template.clone()
        } else {
            None
        };
        let whole = expected == &event.fields;
        if !seen.insert((event.source.clone(), key_template, route, whole)) {
            continue;
        }
        tests.push(unit_test(
            event,
            reduced.template.as_ref(),
            route,
            expected,
        )?);
    }
    Ok(tests)
}

fn unit_test(
    event: &Event,
    template: Option<&TemplateId>,
    route: &str,
    expected: &Map<String, Value>,
) -> Result<Value, VectorError> {
    let component = Components::for_source(&event.source).program;
    let input =
        serde_json::to_string(&event.fields).map_err(|e| VectorError::Config(e.to_string()))?;
    let output = serde_json::to_string(expected).map_err(|e| VectorError::Config(e.to_string()))?;
    let template_check = match template {
        Some(id) => format!(
            "%sluice.{TEMPLATE_METADATA} == {}",
            syntax::string(id.as_str())
        ),
        None => format!("!exists(%sluice.{TEMPLATE_METADATA})"),
    };
    let name = format!(
        "{} {} -> {route} (event {})",
        event.source,
        template.map_or("unclassified", TemplateId::as_str),
        event.id
    );
    Ok(json!({
        "name": name,
        "inputs": [{
            "insert_at": component,
            "type": "vrl",
            "source": format!(". = parse_json!({})", syntax::string(&input)),
        }],
        "outputs": [{
            "extract_from": component,
            "conditions": [{
                "type": "vrl",
                "source": format!(
                    "{template_check} && %sluice.{ROUTE_METADATA} == {} && . == parse_json!({})",
                    syntax::string(route),
                    syntax::string(&output)
                ),
            }],
        }],
    }))
}
